### ISSUE TITLE
memory mapping is broken on ULX3S

### ISSUE THREAD

**Issue by Dolu1990** [SpinalHDL/u-boot#4]
@roman3017 @lawrie 
It seem there is something broken there.

Having 
#define CONFIG_SYS_MALLOC_LEN		SZ_256K

work, and the boot is successfull (read image from sdcard, ... )

But
#define CONFIG_SYS_MALLOC_LEN		SZ_512K

produce the following : 
```
=> boot
4808132 bytes read in 2743 ms (1.7 MiB/s)
3106 bytes read in 13 ms (232.4 KiB/s)
## Booting kernel from Legacy Image at 80000000 ...
Bad Header Checksum
ERROR: can't get kernel image!
=> 
```

To be honnest how u-boot use/map the memory is quite unknown for me.

There is also the save env which crash and corrupt the sdcard.

**Comment by Dolu1990** [comment]
Ahhh not enough space from 0x81F00000 to 0x82000000

**Comment by Dolu1990** [comment]
ahhhh basicaly, CONFIG_MMC_SPI_CRC_ON=n   to boost speed, turn out to make u-boot bugy when that's about to write stuff on the sdcard XD

i will restore CONFIG_MMC_SPI_CRC_ON=y for the moment.

**Comment by roman3017** [comment]
I also need to use  CONFIG_MMC_SPI_CRC_ON=y. For some reason MMC does not work for me without it.
